# -*- coding: utf-8 -*-
"""repos app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10F4Rl0BFnDMnfctQ-Y0pvCWzzajqL4tA
"""

import streamlit as st
from genetic_algorithm import algoritma_genetika
from data import DATASETS
from visualization import buat_grafik


st.set_page_config(
    page_title="Optimasi Tata Letak Rumah Sakit",
    layout="wide"
)


st.title("🏥 Optimasi Tata Letak Departemen Rumah Sakit X")
st.markdown(
"""
Menggunakan:
- Quadratic Assignment Problem (QAP)
- Algoritma Genetika
- Order Crossover (OX)
- Reciprocal Exchange Mutation
"""
)


dataset = st.selectbox(
    "Pilih Ukuran Dataset",
    ["Kecil (n=5)", "Sedang (n=12)", "Besar (n=19)"]
)


pop = st.slider(
    "Population Size",
    10,200,50
)

gen = st.slider(
    "Maksimum Generasi",
    50,1000,500
)


if st.button("🚀 Jalankan Optimasi"):

    with st.spinner("Algoritma genetika berjalan..."):

        best_k, best_z, fitness, history, avg, waktu = \
        algoritma_genetika(
            DATASETS[dataset]["flow"],
            DATASETS[dataset]["dist"],
            DATASETS[dataset]["dept"],
            popsize=pop,
            max_gen=gen
        )


    st.success("Optimasi selesai!")

    col1,col2,col3 = st.columns(3)

    col1.metric(
        "Nilai Objektif Z",
        f"{best_z:,.0f}"
    )

    col2.metric(
        "Fitness",
        f"{fitness:.8f}"
    )

    col3.metric(
        "Waktu",
        f"{waktu:.2f} detik"
    )


    st.subheader("📈 Konvergensi")

    fig = buat_grafik(history,avg)

    st.pyplot(fig)


    st.subheader("📌 Layout Optimal")


    for i,dept in enumerate(best_k):

        st.write(
        f"Lokasi {i+1} → {DATASETS[dataset]['dept'][dept]}"
        )